
#服务端口
server:
  port: 8411
  context-path: /springboot

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lyb
    username: root
    password: wq3776147
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations:
    classpath*:mapper/**.xml